const blogCategories = [
  "Technology",
  "Programming",
  "Science",
  "Health",
  "Lifestyle",
  "Travel",
  "Business",
  "Finance",
  "Education",
  "Productivity",
  "Design",
  "Art",
  "Photography",
  "Food",
  "Culture",
  "Politics",
  "Environment",
  "Personal Development",
  "Sports",
  "Entertainment",
  "Books",
  "Music",
  "Startups",
  "Marketing",
  "Psychology",
];

module.exports = blogCategories;
